'use strict';

const SUPABASE_URL='https://jzqhjoudeetjrhlhiaho.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_LHfM8AdX_u2PzdQPk7CZyQ_e8fEkcpl';
const formatarMoeda=valor=>Number(valor).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const escaparHtml=texto=>{const el=document.createElement('div');el.textContent=String(texto??'');return el.innerHTML};
const headersPublicos=extras=>({apikey:SUPABASE_PUBLISHABLE_KEY,...extras});
const reduzirMovimento=matchMedia('(prefers-reduced-motion: reduce)').matches;

/* Navegação, vídeo e microinterações */
const menuToggle=document.querySelector('.menu-toggle');
const navLinks=document.getElementById('nav-links');
menuToggle.addEventListener('click',()=>{const abrir=!navLinks.classList.contains('open');navLinks.classList.toggle('open',abrir);menuToggle.classList.toggle('open',abrir);menuToggle.setAttribute('aria-expanded',String(abrir))});
navLinks.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navLinks.classList.remove('open');menuToggle.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}));

const siteNav=document.querySelector('.site-nav');
const secoesDoMenu=[...document.querySelectorAll('main>header,main>section,.site-footer')];
let quadroTemaMenu=0;
function atualizarTemaMenu(){quadroTemaMenu=0;const linhaLeitura=siteNav.offsetHeight/2;const secaoAtual=secoesDoMenu.find(secao=>{const limites=secao.getBoundingClientRect();return limites.top<=linhaLeitura&&limites.bottom>linhaLeitura});const fundoEscuro=secaoAtual?.matches('.hero,.invitation-section,.gallery,.site-footer');siteNav.classList.toggle('nav-on-light',Boolean(secaoAtual&&!fundoEscuro))}
function agendarTemaMenu(){if(!quadroTemaMenu)quadroTemaMenu=requestAnimationFrame(atualizarTemaMenu)}
addEventListener('scroll',agendarTemaMenu,{passive:true});
addEventListener('resize',agendarTemaMenu);
requestAnimationFrame(atualizarTemaMenu);

const heroVideo=document.getElementById('hero-video');
const soundToggle=document.getElementById('sound-toggle');
function atualizarControleSom(){const temAudio=Boolean(heroVideo.audioTracks?.length||heroVideo.mozHasAudio||heroVideo.webkitAudioDecodedByteCount);soundToggle.hidden=!temAudio}
heroVideo.addEventListener('loadedmetadata',atualizarControleSom);
heroVideo.addEventListener('timeupdate',atualizarControleSom);
heroVideo.addEventListener('canplay',()=>document.body.classList.add('video-ready'),{once:true});
heroVideo.addEventListener('error',()=>{document.body.classList.remove('video-ready');soundToggle.hidden=true});
soundToggle.addEventListener('click',async()=>{try{heroVideo.muted=!heroVideo.muted;if(heroVideo.paused)await heroVideo.play();const ativo=!heroVideo.muted;soundToggle.setAttribute('aria-pressed',String(ativo));document.getElementById('sound-label').textContent=ativo?'Desativar som':'Ativar som'}catch{soundToggle.hidden=true}});

document.getElementById('open-invite').addEventListener('click',function(){const card=document.getElementById('invitation-card');const aberto=card.classList.toggle('open');this.setAttribute('aria-expanded',String(aberto));if(aberto)criarPetalas(innerWidth/2,innerHeight/2,12)});

document.querySelectorAll('.info-accordions details').forEach(topico=>{
  const resumo=topico.querySelector('summary');
  const conteudo=resumo.nextElementSibling;
  resumo.addEventListener('click',evento=>{
    evento.preventDefault();
    if(topico.dataset.animating==='true')return;
    const abrir=!topico.open;
    if(reduzirMovimento){topico.open=abrir;return}
    if(abrir)topico.open=true;
    else topico.classList.add('is-closing');
    const alturaInicial=abrir?resumo.offsetHeight:topico.offsetHeight;
    const alturaFinal=abrir?resumo.offsetHeight+conteudo.offsetHeight:resumo.offsetHeight;
    topico.dataset.animating='true';
    topico.style.overflow='hidden';
    const animacaoTopico=topico.animate({height:[`${alturaInicial}px`,`${alturaFinal}px`]},{duration:440,easing:'cubic-bezier(.22,.72,.2,1)'});
    const animacaoConteudo=conteudo.animate({opacity:abrir?[0,1]:[1,0],transform:abrir?['translateY(-12px)','translateY(0)']:['translateY(0)','translateY(-10px)']},{duration:abrir?390:260,easing:'ease-out'});
    Promise.all([animacaoTopico.finished,animacaoConteudo.finished]).then(()=>{
      if(!abrir)topico.open=false;
      topico.classList.remove('is-closing');
      topico.style.removeProperty('overflow');
      delete topico.dataset.animating;
    }).catch(()=>{});
  });
});

let observador;
function observarEntradas(){const itens=document.querySelectorAll('.reveal:not([data-seen])');if(!('IntersectionObserver'in window)||reduzirMovimento){itens.forEach(item=>item.classList.add('visible'));return}if(!observador)observador=new IntersectionObserver(entradas=>entradas.forEach(entrada=>{if(entrada.isIntersecting){entrada.target.classList.add('visible');observador.unobserve(entrada.target)}}),{threshold:.12,rootMargin:'0px 0px -35px'});itens.forEach(item=>{item.dataset.seen='true';observador.observe(item)})}

const paredePolaroides=document.getElementById('polaroid-wall');
const polaroidesScroll=[...paredePolaroides.querySelectorAll('.polaroid')];
let quadroPolaroides;
function atualizarPolaroidesNoScroll(){quadroPolaroides=0;if(reduzirMovimento)return;const parede=paredePolaroides.getBoundingClientRect();const alcanceEscala=Math.max(innerHeight*.65,430);const alcanceSaida=Math.max(innerHeight*1.35,900);polaroidesScroll.forEach((foto,indice)=>{const topoOriginal=parede.top+foto.offsetTop;const progressoEscala=Math.min(1,Math.max(0,(innerHeight*.9-topoOriginal)/alcanceEscala));const escalaSuave=progressoEscala*progressoEscala*(3-2*progressoEscala);const progressoSaida=Math.min(1,Math.max(0,(innerHeight*.72-topoOriginal)/alcanceSaida));const saidaSuave=progressoSaida*progressoSaida*(3-2*progressoSaida);const direcao=indice%2===0?-1:1;const distancia=innerWidth*.72+foto.offsetWidth;foto.style.setProperty('--scroll-scale',String(.72+escalaSuave*.28));foto.style.setProperty('--drift-x',`${direcao*saidaSuave*distancia}px`)})}
function agendarPolaroides(){if(!quadroPolaroides)quadroPolaroides=requestAnimationFrame(atualizarPolaroidesNoScroll)}
if(!reduzirMovimento){addEventListener('scroll',agendarPolaroides,{passive:true});addEventListener('resize',agendarPolaroides);requestAnimationFrame(atualizarPolaroidesNoScroll)}

const lightbox=document.getElementById('lightbox');
const lightboxImage=document.getElementById('lightbox-image');
const lightboxCaption=document.getElementById('lightbox-caption');
function abrirFoto(item){lightboxImage.src=item.dataset.lightbox;lightboxImage.alt=item.querySelector('img')?.alt||'';lightboxCaption.textContent=item.dataset.caption||'';lightbox.hidden=false;document.body.classList.add('modal-open');lightbox.querySelector('.lightbox-close').focus()}
function fecharFoto(){lightbox.hidden=true;document.body.classList.remove('modal-open')}
document.querySelectorAll('[data-lightbox]').forEach(item=>{item.addEventListener('click',()=>abrirFoto(item));item.addEventListener('keydown',evento=>{if(evento.key==='Enter'||evento.key===' '){evento.preventDefault();abrirFoto(item)}})});
lightbox.querySelector('.lightbox-close').addEventListener('click',fecharFoto);lightbox.addEventListener('click',evento=>{if(evento.target===lightbox)fecharFoto()});

const coresPetala=['#ffb3bd','#fae86a','#43b02a','#fe8111','#cd0f4d'];
function criarPetalas(x,y,total=5){if(reduzirMovimento)return;for(let i=0;i<total;i++){const petala=document.createElement('i');petala.className='petal-pop';petala.style.left=x+'px';petala.style.top=y+'px';petala.style.background=coresPetala[i%coresPetala.length];petala.style.setProperty('--x',`${(Math.random()-.5)*170}px`);petala.style.setProperty('--y',`${(Math.random()-.75)*190}px`);document.body.appendChild(petala);setTimeout(()=>petala.remove(),950)}}
document.addEventListener('click',evento=>{if(evento.target.closest('button,.polaroid')&&!evento.target.closest('.admin-panel'))criarPetalas(evento.clientX,evento.clientY,4)});

/* Contagem regressiva e calendário */
const casamento=new Date(document.querySelector('.countdown').dataset.date);
function atualizarContagem(){const distancia=Math.max(0,casamento-Date.now());const dias=Math.floor(distancia/86400000);const horas=Math.floor(distancia%86400000/3600000);const minutos=Math.floor(distancia%3600000/60000);const segundos=Math.floor(distancia%60000/1000);document.getElementById('count-days').textContent=String(dias).padStart(3,'0');document.getElementById('count-hours').textContent=String(horas).padStart(2,'0');document.getElementById('count-minutes').textContent=String(minutos).padStart(2,'0');document.getElementById('count-seconds').textContent=String(segundos).padStart(2,'0')}
atualizarContagem();setInterval(atualizarContagem,1000);
document.getElementById('calendar-button').addEventListener('click',()=>{const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Stefany e Pedro//Casamento//PT','BEGIN:VEVENT','UID:casamento-stefany-pedro-20270418','DTSTAMP:20260819T100000Z','DTSTART:20270418T190000Z','DTEND:20270419T020000Z','SUMMARY:Casamento de Stefany e Pedro','LOCATION:Casa Pier - Espírito Santo','DESCRIPTION:Vamos celebrar juntos!','END:VEVENT','END:VCALENDAR'].join('\r\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));link.download='save-the-date-stefany-e-pedro.ics';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500)});

/* Sessão administrativa */
let sessaoAdmin;
try{sessaoAdmin=JSON.parse(sessionStorage.getItem('sessaoAdminSupabase'))||null}catch{sessaoAdmin=null}
function mensagemAdmin(texto,erro=false){const area=document.getElementById('admin-auth-status');area.textContent=texto;area.classList.toggle('error',erro)}
function guardarSessaoAdmin(dados){sessaoAdmin={access_token:dados.access_token,refresh_token:dados.refresh_token,user:dados.user,expires_at:Date.now()+(Number(dados.expires_in)||3600)*1000};sessionStorage.setItem('sessaoAdminSupabase',JSON.stringify(sessaoAdmin));atualizarInterfaceAdmin()}
function limparSessaoAdmin(){sessaoAdmin=null;sessionStorage.removeItem('sessaoAdminSupabase');atualizarInterfaceAdmin()}
function atualizarInterfaceAdmin(){const conectado=Boolean(sessaoAdmin?.access_token);document.getElementById('admin-desconectado').hidden=conectado;document.getElementById('admin-conectado').hidden=!conectado;document.getElementById('admin-email-logado').textContent=conectado?(sessaoAdmin.user?.email||'administrador'):'';document.getElementById('btn-salvar-pix').disabled=!conectado;document.getElementById('btn-salvar-convidado').disabled=!conectado;document.querySelectorAll('.btn-convidado,.admin-delete').forEach(botao=>botao.disabled=!conectado)}
async function renovarSessaoAdmin(){if(!sessaoAdmin?.refresh_token)return null;const resposta=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:headersPublicos({'Content-Type':'application/json'}),body:JSON.stringify({refresh_token:sessaoAdmin.refresh_token})});if(!resposta.ok){limparSessaoAdmin();return null}const dados=await resposta.json();guardarSessaoAdmin(dados);return sessaoAdmin.access_token}
async function tokenAdmin(){if(!sessaoAdmin?.access_token)return null;if(Number(sessaoAdmin.expires_at)>Date.now()+60000)return sessaoAdmin.access_token;return renovarSessaoAdmin()}
async function contaEhAdministradora(token,userId){const resposta=await fetch(SUPABASE_URL+'/rest/v1/site_admins?select=user_id&user_id=eq.'+encodeURIComponent(userId)+'&limit=1',{headers:headersPublicos({Authorization:'Bearer '+token})});return resposta.ok&&(await resposta.json()).length>0}
document.getElementById('form-admin-login').addEventListener('submit',async function(evento){evento.preventDefault();const botao=this.querySelector('button[type=submit]');botao.disabled=true;mensagemAdmin('Entrando...');try{const resposta=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:headersPublicos({'Content-Type':'application/json'}),body:JSON.stringify({email:document.getElementById('admin-email').value.trim(),password:document.getElementById('admin-senha').value})});const dados=await resposta.json();if(!resposta.ok)throw new Error(dados.error_description||dados.msg||'E-mail ou senha inválidos.');if(!(await contaEhAdministradora(dados.access_token,dados.user.id)))throw new Error('Esta conta não está autorizada como administradora.');guardarSessaoAdmin(dados);this.reset();mensagemAdmin('Acesso liberado.');await Promise.all([carregarConvidadosAdmin(),carregarRespostasAdmin(),carregarMensagensAdmin()])}catch(erro){limparSessaoAdmin();mensagemAdmin(erro.message||'Não foi possível entrar.',true)}finally{botao.disabled=false;atualizarInterfaceAdmin()}});
async function sairAdmin(){const token=await tokenAdmin();if(token)fetch(SUPABASE_URL+'/auth/v1/logout',{method:'POST',headers:headersPublicos({Authorization:'Bearer '+token})}).catch(()=>{});limparSessaoAdmin();mensagemAdmin('Sessão encerrada.')}
async function restaurarSessaoAdmin(){atualizarInterfaceAdmin();if(!sessaoAdmin)return;const token=await tokenAdmin();if(!token||!(await contaEhAdministradora(token,sessaoAdmin.user.id))){limparSessaoAdmin();return}atualizarInterfaceAdmin();mensagemAdmin('Sessão restaurada.')}
function toggleAdmin(){if(document.body.classList.contains('admin-route')){location.href=location.pathname;return}const painel=document.getElementById('painel-admin');const abrir=painel.hidden;painel.hidden=!abrir;document.querySelectorAll('[onclick="toggleAdmin()"]').forEach(botao=>botao.setAttribute('aria-expanded',String(abrir)));if(abrir){painel.scrollIntoView({behavior:'smooth',block:'start'});if(sessaoAdmin)Promise.all([carregarConvidadosAdmin(),carregarRespostasAdmin(),carregarMensagensAdmin()])}}

/* PIX e presentes */
let chavePixCasal=localStorage.getItem('chavePix')||'';
document.getElementById('config-pix').value=chavePixCasal;
function statusPix(texto,erro=false){const area=document.getElementById('pix-admin-status');area.textContent=texto;area.classList.toggle('error',erro)}
async function carregarPixGlobal(){try{const resposta=await fetch(SUPABASE_URL+'/rest/v1/site_settings?select=setting_value&setting_key=eq.pix_key&limit=1',{headers:headersPublicos()});if(!resposta.ok)throw new Error();const dados=await resposta.json();if(dados.length){chavePixCasal=dados[0].setting_value;localStorage.setItem('chavePix',chavePixCasal);document.getElementById('config-pix').value=chavePixCasal}}catch{statusPix('Usando a configuração salva neste navegador.',true)}finally{atualizarDisponibilidadeContribuicao()}}
async function salvarPix(){const token=await tokenAdmin();const valor=document.getElementById('config-pix').value.trim();if(!token){mensagemAdmin('Entre antes de salvar o PIX.',true);return}if(!valor){statusPix('Cole um código PIX.',true);return}const botao=document.getElementById('btn-salvar-pix');botao.disabled=true;statusPix('Salvando...');try{const resposta=await fetch(SUPABASE_URL+'/rest/v1/site_settings?on_conflict=setting_key',{method:'POST',headers:headersPublicos({Authorization:'Bearer '+token,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'}),body:JSON.stringify({setting_key:'pix_key',setting_value:valor,updated_at:new Date().toISOString()})});if(!resposta.ok)throw new Error('O Supabase não permitiu salvar.');chavePixCasal=valor;localStorage.setItem('chavePix',valor);atualizarDisponibilidadeContribuicao();statusPix('PIX salvo para todos os convidados.')}catch(erro){statusPix(erro.message,true)}finally{botao.disabled=!sessaoAdmin}}

const campoValorContribuicao=document.getElementById('pix-contribution-value');
const botaoGerarContribuicao=document.getElementById('generate-contribution-pix');
const resultadoContribuicao=document.getElementById('pix-contribution-result');
const statusContribuicao=document.getElementById('pix-contribution-status');
let codigoPixContribuicao='';
function atualizarDisponibilidadeContribuicao(){const disponivel=Boolean(chavePixCasal);botaoGerarContribuicao.disabled=!disponivel;statusContribuicao.textContent=disponivel?'':'A contribuição por PIX estará disponível em breve.';statusContribuicao.classList.toggle('error',!disponivel)}
function crc16Pix(texto){let crc=0xffff;for(const byte of new TextEncoder().encode(texto)){crc^=byte<<8;for(let bit=0;bit<8;bit++)crc=crc&0x8000?(crc<<1^0x1021)&0xffff:crc<<1&0xffff}return crc.toString(16).toUpperCase().padStart(4,'0')}
function separarCamposPix(codigo){const campos=[];let indice=0;while(indice<codigo.length){if(indice+4>codigo.length)throw new Error('Código PIX incompleto.');const tag=codigo.slice(indice,indice+2);const tamanhoTexto=codigo.slice(indice+2,indice+4);if(!/^\d{2}$/.test(tamanhoTexto))throw new Error('Código PIX inválido.');const tamanho=Number(tamanhoTexto);const fim=indice+4+tamanho;if(fim>codigo.length)throw new Error('Código PIX incompleto.');campos.push({tag,valor:codigo.slice(indice+4,fim)});indice=fim}return campos}
function criarPixComValor(codigoOriginal,valor){const codigo=String(codigoOriginal||'').replace(/\s+/g,'');const campos=separarCamposPix(codigo).filter(campo=>campo.tag!=='54'&&campo.tag!=='63');if(!campos.some(campo=>campo.tag==='00')||!campos.some(campo=>campo.tag==='53'&&campo.valor==='986'))throw new Error('Cadastre no painel um código PIX Copia e Cola válido.');const valorFormatado=Number(valor).toFixed(2);const campoValor={tag:'54',valor:valorFormatado};const indiceMoeda=campos.findIndex(campo=>campo.tag==='53');campos.splice(indiceMoeda+1,0,campoValor);const base=campos.map(campo=>campo.tag+String(new TextEncoder().encode(campo.valor).length).padStart(2,'0')+campo.valor).join('')+'6304';return base+crc16Pix(base)}
function desenharQrCodePix(codigo){const area=document.getElementById('pix-contribution-qrcode');area.innerHTML='';if(typeof QRCode==='undefined'){area.closest('.pix-qrcode-frame').hidden=true;return false}area.closest('.pix-qrcode-frame').hidden=false;new QRCode(area,{text:codigo,width:220,height:220,colorDark:'#441529',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});return true}
document.querySelectorAll('.pix-amount-option').forEach(botao=>botao.addEventListener('click',()=>{campoValorContribuicao.value=botao.dataset.value;document.querySelectorAll('.pix-amount-option').forEach(item=>item.setAttribute('aria-pressed',String(item===botao)));campoValorContribuicao.focus()}));
campoValorContribuicao.addEventListener('input',()=>document.querySelectorAll('.pix-amount-option').forEach(item=>item.setAttribute('aria-pressed','false')));
document.getElementById('pix-contribution-form').addEventListener('submit',evento=>{evento.preventDefault();const valor=Number(campoValorContribuicao.value);statusContribuicao.classList.remove('error');if(!Number.isFinite(valor)||valor<1||valor>99999999.99){statusContribuicao.textContent='Escolha um valor válido a partir de R$ 1,00.';statusContribuicao.classList.add('error');return}try{codigoPixContribuicao=criarPixComValor(chavePixCasal,valor);const temQr=desenharQrCodePix(codigoPixContribuicao);document.getElementById('pix-contribution-selected').innerHTML=`PIX no valor de <strong>${formatarMoeda(valor)}</strong>`;document.getElementById('pix-copy-status').textContent='';resultadoContribuicao.hidden=false;statusContribuicao.textContent=temQr?'PIX gerado com carinho.':'PIX gerado. Use o botão abaixo para copiar o código.';criarPetalas(innerWidth*.72,innerHeight*.5,12)}catch(erro){resultadoContribuicao.hidden=true;statusContribuicao.textContent=erro.message||'Não foi possível gerar o PIX.';statusContribuicao.classList.add('error')}});
document.getElementById('copy-contribution-pix').addEventListener('click',async function(){if(!codigoPixContribuicao)return;const status=document.getElementById('pix-copy-status');try{await navigator.clipboard.writeText(codigoPixContribuicao);status.textContent='Código PIX copiado!';this.textContent='Código copiado!'}catch{prompt('Copie o código PIX:',codigoPixContribuicao);status.textContent='Selecione e copie o código exibido.'}});
atualizarDisponibilidadeContribuicao();

/* RSVP e mensagens */
async function inserirPublico(tabela,corpo){const resposta=await fetch(`${SUPABASE_URL}/rest/v1/${tabela}`,{method:'POST',headers:headersPublicos({'Content-Type':'application/json',Prefer:'return=minimal'}),body:JSON.stringify(corpo)});if(!resposta.ok){const dados=await resposta.json().catch(()=>({}));throw new Error(dados.message||'Não foi possível enviar agora.')}}
async function chamarRpc(nome,corpo){const resposta=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${nome}`,{method:'POST',headers:headersPublicos({'Content-Type':'application/json'}),body:JSON.stringify(corpo)});const dados=await resposta.json().catch(()=>null);if(!resposta.ok){const erro=new Error(dados?.message||'Não foi possível enviar agora.');erro.status=resposta.status;throw erro}return dados}
function definirStatus(id,texto,tipo=''){const area=document.getElementById(id);area.textContent=texto;area.className='form-status '+tipo}
const rsvpName=document.getElementById('rsvp-name'),rsvpGuestId=document.getElementById('rsvp-guest-id'),guestSuggestions=document.getElementById('guest-suggestions'),guestLimit=document.getElementById('rsvp-guest-limit');
let buscaConvidadoTimer=0,buscaConvidadoAtual=0,listaFechadaDisponivel=true;
function esconderSugestoes(){guestSuggestions.hidden=true;rsvpName.setAttribute('aria-expanded','false')}
function selecionarConvidado(convidado){rsvpName.value=convidado.guest_name;rsvpGuestId.value=convidado.guest_id;guestLimit.textContent='Nome selecionado.';guestLimit.classList.add('selected');esconderSugestoes();definirStatus('rsvp-status','')}
function mostrarSugestoes(convidados){guestSuggestions.innerHTML='';if(!convidados.length){guestSuggestions.innerHTML='<span class="guest-suggestions-empty">Nenhum nome encontrado. Confira como está no convite.</span>'}else convidados.forEach(convidado=>{const botao=document.createElement('button');botao.type='button';botao.className='guest-suggestion';botao.setAttribute('role','option');botao.textContent=convidado.guest_name;botao.addEventListener('click',()=>selecionarConvidado(convidado));guestSuggestions.appendChild(botao)});guestSuggestions.hidden=false;rsvpName.setAttribute('aria-expanded','true')}
rsvpName.addEventListener('input',()=>{rsvpGuestId.value='';guestLimit.classList.remove('selected');const termo=rsvpName.value.trim();clearTimeout(buscaConvidadoTimer);if(termo.length<3){esconderSugestoes();guestLimit.textContent='Digite pelo menos 3 letras e selecione seu nome.';return}guestLimit.textContent='Buscando seu convite...';const numero=++buscaConvidadoAtual;buscaConvidadoTimer=setTimeout(async()=>{try{const dados=await chamarRpc('search_wedding_guests',{search_term:termo});listaFechadaDisponivel=true;if(numero===buscaConvidadoAtual){mostrarSugestoes(Array.isArray(dados)?dados:[]);guestLimit.textContent='Selecione seu nome na lista abaixo.'}}catch(erro){if(numero===buscaConvidadoAtual){esconderSugestoes();listaFechadaDisponivel=erro.status!==404;guestLimit.textContent=listaFechadaDisponivel?'Não foi possível consultar a lista agora.':'Digite seu nome completo para confirmar.'}}},280)});
document.addEventListener('click',evento=>{if(!evento.target.closest('.guest-name-field'))esconderSugestoes()});
document.getElementById('rsvp-form').addEventListener('submit',async function(evento){evento.preventDefault();if(this.website.value)return;const botao=this.querySelector('button[type=submit]');const dados=new FormData(this);if(!rsvpGuestId.value&&listaFechadaDisponivel){definirStatus('rsvp-status','Digite seu nome e selecione uma opção da lista.','error');rsvpName.focus();return}botao.disabled=true;definirStatus('rsvp-status','Enviando...');try{if(rsvpGuestId.value)await chamarRpc('submit_wedding_rsvp',{p_guest_id:rsvpGuestId.value,p_attending:dados.get('attendance')==='sim',p_guest_count:1,p_note:null});else await inserirPublico('guest_responses',{guest_name:String(dados.get('name')).trim(),attending:dados.get('attendance')==='sim',guest_count:1,note:null});definirStatus('rsvp-status','Presença registrada! Você pode enviar novamente se precisar atualizar.','success');this.reset();rsvpGuestId.value='';guestLimit.textContent='Digite pelo menos 3 letras e selecione seu nome.';guestLimit.classList.remove('selected');criarPetalas(innerWidth*.73,innerHeight*.55,16)}catch(erro){definirStatus('rsvp-status',erro.message,'error')}finally{botao.disabled=false}});
document.getElementById('message-form').addEventListener('submit',async function(evento){evento.preventDefault();if(this.website.value)return;const botao=this.querySelector('button[type=submit]');const dados=new FormData(this);botao.disabled=true;definirStatus('message-status','Guardando sua mensagem...');try{await inserirPublico('guest_messages',{guest_name:String(dados.get('name')).trim(),message:String(dados.get('message')).trim()});definirStatus('message-status','Mensagem enviada com carinho!','success');this.reset();criarPetalas(innerWidth*.72,innerHeight*.5,18)}catch(erro){definirStatus('message-status',erro.message,'error')}finally{botao.disabled=false}});

let convidadosAdmin=[];
function statusConvidadoAdmin(texto,erro=false){const area=document.getElementById('convidado-admin-status');area.textContent=texto;area.classList.toggle('error',erro)}
async function carregarConvidadosAdmin(){const token=await tokenAdmin();if(!token)return;const area=document.getElementById('lista-admin-convidados');area.innerHTML='<p>Carregando...</p>';const resposta=await fetch(SUPABASE_URL+'/rest/v1/wedding_guests?select=id,display_name,max_guests,active&order=display_name.asc',{headers:headersPublicos({Authorization:'Bearer '+token})});if(!resposta.ok){area.innerHTML='<p>Não foi possível carregar.</p>';return}convidadosAdmin=await resposta.json();area.innerHTML=convidadosAdmin.length?'':'<p>Nenhum convidado cadastrado ainda.</p>';convidadosAdmin.forEach(item=>{const id=String(item.id);area.insertAdjacentHTML('beforeend',`<div class="item-admin"><div><strong>${escaparHtml(item.display_name)}</strong><small>Até ${item.max_guests} pessoa(s) · ${item.active?'ativo':'desativado'}</small></div><div class="item-admin-actions"><button class="btn-convidado" onclick="alternarConvidado('${id}',${!item.active})">${item.active?'Desativar':'Ativar'}</button><button class="btn-convidado" onclick="excluirConvidado('${id}')">Excluir</button></div></div>`)});atualizarInterfaceAdmin()}
document.getElementById('form-add-convidado').addEventListener('submit',async function(evento){evento.preventDefault();const token=await tokenAdmin();if(!token)return;const botao=document.getElementById('btn-salvar-convidado');const nome=document.getElementById('convidado-nome').value.trim();const limite=Number(document.getElementById('convidado-limite').value);botao.disabled=true;statusConvidadoAdmin('Adicionando...');try{const resposta=await fetch(SUPABASE_URL+'/rest/v1/wedding_guests',{method:'POST',headers:headersPublicos({Authorization:'Bearer '+token,'Content-Type':'application/json',Prefer:'return=minimal'}),body:JSON.stringify({display_name:nome,max_guests:limite})});const dados=await resposta.json().catch(()=>({}));if(!resposta.ok)throw new Error(dados.code==='23505'?'Este nome já está na lista.':dados.message||'Não foi possível adicionar.');this.reset();document.getElementById('convidado-limite').value=1;statusConvidadoAdmin('Convidado adicionado.');await carregarConvidadosAdmin()}catch(erro){statusConvidadoAdmin(erro.message,true)}finally{botao.disabled=!sessaoAdmin}});
async function alternarConvidado(id,ativo){const token=await tokenAdmin();if(!token)return;const resposta=await fetch(SUPABASE_URL+'/rest/v1/wedding_guests?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:headersPublicos({Authorization:'Bearer '+token,'Content-Type':'application/json'}),body:JSON.stringify({active:ativo,updated_at:new Date().toISOString()})});if(resposta.ok){statusConvidadoAdmin(ativo?'Convidado ativado.':'Convidado desativado.');await carregarConvidadosAdmin()}else statusConvidadoAdmin('Não foi possível alterar este convidado.',true)}
async function excluirConvidado(id){const token=await tokenAdmin();const convidado=convidadosAdmin.find(item=>item.id===id);if(!token||!convidado||!confirm(`Excluir “${convidado.display_name}” e a confirmação de presença vinculada?`))return;statusConvidadoAdmin('Excluindo...');try{const respostaRsvp=await fetch(SUPABASE_URL+'/rest/v1/guest_responses?guest_id=eq.'+encodeURIComponent(id),{method:'DELETE',headers:headersPublicos({Authorization:'Bearer '+token,Prefer:'return=minimal'})});if(!respostaRsvp.ok)throw new Error('Não foi possível excluir a confirmação vinculada.');const resposta=await fetch(SUPABASE_URL+'/rest/v1/wedding_guests?id=eq.'+encodeURIComponent(id),{method:'DELETE',headers:headersPublicos({Authorization:'Bearer '+token,Prefer:'return=minimal'})});if(!resposta.ok)throw new Error('Não foi possível excluir o convidado.');statusConvidadoAdmin('Convidado e confirmação excluídos.');await Promise.all([carregarConvidadosAdmin(),carregarRespostasAdmin()])}catch(erro){statusConvidadoAdmin(erro.message||'Não foi possível excluir.',true)}}

function statusRegistroAdmin(id,texto,erro=false){const area=document.getElementById(id);area.textContent=texto;area.classList.toggle('error',erro)}
async function carregarRespostasAdmin(){const token=await tokenAdmin();if(!token)return;const area=document.getElementById('lista-admin-rsvp');area.innerHTML='<p>Carregando...</p>';const resposta=await fetch(SUPABASE_URL+'/rest/v1/guest_responses?select=id,guest_id,guest_name,attending,guest_count,note,created_at&order=created_at.desc',{headers:headersPublicos({Authorization:'Bearer '+token})});if(!resposta.ok){area.innerHTML='<p>Não foi possível carregar.</p>';return}const dados=await resposta.json();area.innerHTML=dados.length?'':'<p>Nenhuma confirmação ainda.</p>';dados.forEach(item=>area.insertAdjacentHTML('beforeend',`<div class="admin-data wedding-response"><strong>${escaparHtml(item.guest_name)}</strong><span>${item.attending?'Vai comparecer':'Não comparece'}</span><span>${item.guest_count} pessoa(s)</span><span>${escaparHtml(item.note||'—')}</span><button class="admin-delete" type="button" onclick="excluirRespostaAdmin(${Number(item.id)})">Excluir</button></div>`));atualizarInterfaceAdmin()}
async function excluirRespostaAdmin(id){const token=await tokenAdmin();if(!token||!confirm('Excluir esta confirmação de presença?'))return;statusRegistroAdmin('rsvp-admin-status','Excluindo...');const resposta=await fetch(SUPABASE_URL+'/rest/v1/guest_responses?id=eq.'+encodeURIComponent(id),{method:'DELETE',headers:headersPublicos({Authorization:'Bearer '+token,Prefer:'return=minimal'})});if(resposta.ok){statusRegistroAdmin('rsvp-admin-status','Confirmação excluída.');await carregarRespostasAdmin()}else statusRegistroAdmin('rsvp-admin-status','Não foi possível excluir a confirmação.',true)}

async function carregarMensagensAdmin(){const token=await tokenAdmin();if(!token)return;const area=document.getElementById('lista-admin-mensagens');area.innerHTML='<p>Carregando...</p>';const resposta=await fetch(SUPABASE_URL+'/rest/v1/guest_messages?select=id,guest_name,message,created_at&order=created_at.desc',{headers:headersPublicos({Authorization:'Bearer '+token})});if(!resposta.ok){area.innerHTML='<p>Não foi possível carregar.</p>';return}const dados=await resposta.json();area.innerHTML=dados.length?'':'<p>Nenhuma mensagem ainda.</p>';dados.forEach(item=>area.insertAdjacentHTML('beforeend',`<div class="admin-data message"><strong>${escaparHtml(item.guest_name)}</strong><span>${escaparHtml(item.message)}</span><time>${new Date(item.created_at).toLocaleDateString('pt-BR')}</time><button class="admin-delete" type="button" onclick="excluirMensagemAdmin(${Number(item.id)})">Excluir</button></div>`));atualizarInterfaceAdmin()}
async function excluirMensagemAdmin(id){const token=await tokenAdmin();if(!token||!confirm('Excluir esta mensagem?'))return;statusRegistroAdmin('mensagem-admin-status','Excluindo...');const resposta=await fetch(SUPABASE_URL+'/rest/v1/guest_messages?id=eq.'+encodeURIComponent(id),{method:'DELETE',headers:headersPublicos({Authorization:'Bearer '+token,Prefer:'return=minimal'})});if(resposta.ok){statusRegistroAdmin('mensagem-admin-status','Mensagem excluída.');await carregarMensagensAdmin()}else statusRegistroAdmin('mensagem-admin-status','Não foi possível excluir a mensagem.',true)}

document.addEventListener('keydown',evento=>{if(evento.key==='Escape'){fecharFoto();navLinks.classList.remove('open');menuToggle.classList.remove('open')}});

restaurarSessaoAdmin();carregarPixGlobal();observarEntradas();
const acessoAdminPorUrl=new URLSearchParams(location.search).get('admin')==='1';
if(acessoAdminPorUrl){document.body.classList.add('admin-route');const painel=document.getElementById('painel-admin');painel.hidden=false;if(sessaoAdmin)Promise.all([carregarConvidadosAdmin(),carregarRespostasAdmin(),carregarMensagensAdmin()])}
else if(location.hash)requestAnimationFrame(()=>{const alvo=document.querySelector(location.hash);alvo?.querySelectorAll('.reveal').forEach(item=>item.classList.add('visible'));alvo?.scrollIntoView({block:'start'})});
