'use strict';

const SUPABASE_URL='https://jzqhjoudeetjrhlhiaho.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_LHfM8AdX_u2PzdQPk7CZyQ_e8fEkcpl';
const formatarMoeda=valor=>Number(valor).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const escaparHtml=texto=>{const el=document.createElement('div');el.textContent=String(texto??'');return el.innerHTML};
const lerListaSalva=(chave,padrao)=>{try{const valor=JSON.parse(localStorage.getItem(chave));return Array.isArray(valor)?valor:padrao}catch{return padrao}};
const headersPublicos=extras=>({apikey:SUPABASE_PUBLISHABLE_KEY,...extras});
const reduzirMovimento=matchMedia('(prefers-reduced-motion: reduce)').matches;

/* Navegação, vídeo e microinterações */
const menuToggle=document.querySelector('.menu-toggle');
const navLinks=document.getElementById('nav-links');
menuToggle.addEventListener('click',()=>{const abrir=!navLinks.classList.contains('open');navLinks.classList.toggle('open',abrir);menuToggle.classList.toggle('open',abrir);menuToggle.setAttribute('aria-expanded',String(abrir))});
navLinks.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navLinks.classList.remove('open');menuToggle.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}));

const heroVideo=document.getElementById('hero-video');
const soundToggle=document.getElementById('sound-toggle');
function atualizarControleSom(){const temAudio=Boolean(heroVideo.audioTracks?.length||heroVideo.mozHasAudio||heroVideo.webkitAudioDecodedByteCount);soundToggle.hidden=!temAudio}
heroVideo.addEventListener('loadedmetadata',atualizarControleSom);
heroVideo.addEventListener('timeupdate',atualizarControleSom);
heroVideo.addEventListener('canplay',()=>document.body.classList.add('video-ready'),{once:true});
heroVideo.addEventListener('error',()=>{document.body.classList.remove('video-ready');soundToggle.hidden=true});
soundToggle.addEventListener('click',async()=>{try{heroVideo.muted=!heroVideo.muted;if(heroVideo.paused)await heroVideo.play();const ativo=!heroVideo.muted;soundToggle.setAttribute('aria-pressed',String(ativo));document.getElementById('sound-label').textContent=ativo?'Desativar som':'Ativar som'}catch{soundToggle.hidden=true}});

document.getElementById('open-invite').addEventListener('click',function(){const card=document.getElementById('invitation-card');const aberto=card.classList.toggle('open');this.setAttribute('aria-expanded',String(aberto));if(aberto)criarPetalas(innerWidth/2,innerHeight/2,12)});

let observador;
function observarEntradas(){const itens=document.querySelectorAll('.reveal:not([data-seen])');if(!('IntersectionObserver'in window)||reduzirMovimento){itens.forEach(item=>item.classList.add('visible'));return}if(!observador)observador=new IntersectionObserver(entradas=>entradas.forEach(entrada=>{if(entrada.isIntersecting){entrada.target.classList.add('visible');observador.unobserve(entrada.target)}}),{threshold:.12,rootMargin:'0px 0px -35px'});itens.forEach(item=>{item.dataset.seen='true';observador.observe(item)})}

const paredePolaroides=document.getElementById('polaroid-wall');
const polaroidesScroll=[...paredePolaroides.querySelectorAll('.polaroid')];
let quadroPolaroides;
function atualizarPolaroidesNoScroll(){quadroPolaroides=0;if(reduzirMovimento)return;const parede=paredePolaroides.getBoundingClientRect();const alcance=Math.max(innerHeight*.82,520);polaroidesScroll.forEach((foto,indice)=>{const topoOriginal=parede.top+foto.offsetTop;const progresso=Math.min(1,Math.max(0,(innerHeight*.74-topoOriginal)/alcance));const saida=Math.pow(progresso,1.7);const direcao=indice%2===0?-1:1;const distancia=innerWidth*.92+foto.offsetWidth;foto.style.setProperty('--drift-x',`${direcao*saida*distancia}px`);foto.style.setProperty('--drift-y',`${(indice%2===0?1:-1)*saida*58}px`);foto.style.setProperty('--drift-turn',`${direcao*saida*(13+indice*2)}deg`)})}
function agendarPolaroides(){if(!quadroPolaroides)quadroPolaroides=requestAnimationFrame(atualizarPolaroidesNoScroll)}
if(!reduzirMovimento){addEventListener('scroll',agendarPolaroides,{passive:true});addEventListener('resize',agendarPolaroides);requestAnimationFrame(atualizarPolaroidesNoScroll)}

const lightbox=document.getElementById('lightbox');
const lightboxImage=document.getElementById('lightbox-image');
const lightboxCaption=document.getElementById('lightbox-caption');
function abrirFoto(item){lightboxImage.src=item.dataset.lightbox;lightboxImage.alt=item.querySelector('img')?.alt||'';lightboxCaption.textContent=item.dataset.caption||'';lightbox.hidden=false;document.body.classList.add('modal-open');lightbox.querySelector('.lightbox-close').focus()}
function fecharFoto(){lightbox.hidden=true;document.body.classList.remove('modal-open')}
document.querySelectorAll('[data-lightbox]').forEach(item=>{item.addEventListener('click',()=>abrirFoto(item));item.addEventListener('keydown',evento=>{if(evento.key==='Enter'||evento.key===' '){evento.preventDefault();abrirFoto(item)}})});
lightbox.querySelector('.lightbox-close').addEventListener('click',fecharFoto);lightbox.addEventListener('click',evento=>{if(evento.target===lightbox)fecharFoto()});

const coresPetala=['#ffb3bd','#fae86a','#43b02a','#fe8111','#cd0f4d'];
function criarPetalas(x,y,total=5){if(reduzirMovimento)return;for(let i=0;i<total;i++){const petala=document.createElement('i');petala.className='petal-pop';petala.style.left=x+'px';petala.style.top=y+'px';petala.style.background=coresPetala[i%coresPetala.length];petala.style.setProperty('--x',`${(Math.random()-.5)*170}px`);petala.style.setProperty('--y',`${(Math.random()-.75)*190}px`);document.body.appendChild(petala);setTimeout(()=>petala.remove(),950)}}
document.addEventListener('click',evento=>{if(evento.target.closest('button,.polaroid')&&!evento.target.closest('.admin-panel'))criarPetalas(evento.clientX,evento.clientY,4)});

/* Contagem regressiva e calendário */
const casamento=new Date(document.querySelector('.countdown').dataset.date);
function atualizarContagem(){const distancia=Math.max(0,casamento-Date.now());const dias=Math.floor(distancia/86400000);const horas=Math.floor(distancia%86400000/3600000);const minutos=Math.floor(distancia%3600000/60000);const segundos=Math.floor(distancia%60000/1000);document.getElementById('count-days').textContent=String(dias).padStart(3,'0');document.getElementById('count-hours').textContent=String(horas).padStart(2,'0');document.getElementById('count-minutes').textContent=String(minutos).padStart(2,'0');document.getElementById('count-seconds').textContent=String(segundos).padStart(2,'0')}
atualizarContagem();setInterval(atualizarContagem,1000);
document.getElementById('calendar-button').addEventListener('click',()=>{const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Stefany e Pedro//Casamento//PT','BEGIN:VEVENT','UID:casamento-stefany-pedro-20270418','DTSTAMP:20260819T100000Z','DTSTART:20270418T190000Z','DTEND:20270419T020000Z','SUMMARY:Casamento de Stefany e Pedro','LOCATION:Casa Pier - Espírito Santo','DESCRIPTION:Vamos celebrar juntos!','END:VEVENT','END:VCALENDAR'].join('\r\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));link.download='save-the-date-stefany-e-pedro.ics';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500)});

/* Sessão administrativa */
let sessaoAdmin;
try{sessaoAdmin=JSON.parse(sessionStorage.getItem('sessaoAdminSupabase'))||null}catch{sessaoAdmin=null}
function mensagemAdmin(texto,erro=false){const area=document.getElementById('admin-auth-status');area.textContent=texto;area.classList.toggle('error',erro)}
function guardarSessaoAdmin(dados){sessaoAdmin={access_token:dados.access_token,refresh_token:dados.refresh_token,user:dados.user,expires_at:Date.now()+(Number(dados.expires_in)||3600)*1000};sessionStorage.setItem('sessaoAdminSupabase',JSON.stringify(sessaoAdmin));atualizarInterfaceAdmin()}
function limparSessaoAdmin(){sessaoAdmin=null;sessionStorage.removeItem('sessaoAdminSupabase');atualizarInterfaceAdmin()}
function atualizarInterfaceAdmin(){const conectado=Boolean(sessaoAdmin?.access_token);document.getElementById('admin-desconectado').hidden=conectado;document.getElementById('admin-conectado').hidden=!conectado;document.getElementById('admin-email-logado').textContent=conectado?(sessaoAdmin.user?.email||'administrador'):'';document.getElementById('btn-salvar-presente').disabled=!conectado;document.getElementById('btn-salvar-pix').disabled=!conectado;document.querySelectorAll('.btn-excluir-presente,.btn-editar-presente').forEach(botao=>botao.disabled=!conectado)}
async function renovarSessaoAdmin(){if(!sessaoAdmin?.refresh_token)return null;const resposta=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:headersPublicos({'Content-Type':'application/json'}),body:JSON.stringify({refresh_token:sessaoAdmin.refresh_token})});if(!resposta.ok){limparSessaoAdmin();return null}const dados=await resposta.json();guardarSessaoAdmin(dados);return sessaoAdmin.access_token}
async function tokenAdmin(){if(!sessaoAdmin?.access_token)return null;if(Number(sessaoAdmin.expires_at)>Date.now()+60000)return sessaoAdmin.access_token;return renovarSessaoAdmin()}
async function contaEhAdministradora(token,userId){const resposta=await fetch(SUPABASE_URL+'/rest/v1/site_admins?select=user_id&user_id=eq.'+encodeURIComponent(userId)+'&limit=1',{headers:headersPublicos({Authorization:'Bearer '+token})});return resposta.ok&&(await resposta.json()).length>0}
document.getElementById('form-admin-login').addEventListener('submit',async function(evento){evento.preventDefault();const botao=this.querySelector('button[type=submit]');botao.disabled=true;mensagemAdmin('Entrando...');try{const resposta=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:headersPublicos({'Content-Type':'application/json'}),body:JSON.stringify({email:document.getElementById('admin-email').value.trim(),password:document.getElementById('admin-senha').value})});const dados=await resposta.json();if(!resposta.ok)throw new Error(dados.error_description||dados.msg||'E-mail ou senha inválidos.');if(!(await contaEhAdministradora(dados.access_token,dados.user.id)))throw new Error('Esta conta não está autorizada como administradora.');guardarSessaoAdmin(dados);this.reset();mensagemAdmin('Acesso liberado.');await Promise.all([carregarRespostasAdmin(),carregarMensagensAdmin()])}catch(erro){limparSessaoAdmin();mensagemAdmin(erro.message||'Não foi possível entrar.',true)}finally{botao.disabled=false;atualizarInterfaceAdmin()}});
async function sairAdmin(){const token=await tokenAdmin();if(token)fetch(SUPABASE_URL+'/auth/v1/logout',{method:'POST',headers:headersPublicos({Authorization:'Bearer '+token})}).catch(()=>{});limparSessaoAdmin();mensagemAdmin('Sessão encerrada.')}
async function restaurarSessaoAdmin(){atualizarInterfaceAdmin();if(!sessaoAdmin)return;const token=await tokenAdmin();if(!token||!(await contaEhAdministradora(token,sessaoAdmin.user.id))){limparSessaoAdmin();return}atualizarInterfaceAdmin();mensagemAdmin('Sessão restaurada.')}
function toggleAdmin(){const painel=document.getElementById('painel-admin');const abrir=painel.hidden;painel.hidden=!abrir;document.querySelectorAll('[onclick="toggleAdmin()"]').forEach(botao=>botao.setAttribute('aria-expanded',String(abrir)));if(abrir){painel.scrollIntoView({behavior:'smooth',block:'start'});if(sessaoAdmin)Promise.all([carregarRespostasAdmin(),carregarMensagensAdmin()])}}

/* PIX e presentes */
let chavePixCasal=localStorage.getItem('chavePix')||'';
document.getElementById('config-pix').value=chavePixCasal;
function statusPix(texto,erro=false){const area=document.getElementById('pix-admin-status');area.textContent=texto;area.classList.toggle('error',erro)}
async function carregarPixGlobal(){try{const resposta=await fetch(SUPABASE_URL+'/rest/v1/site_settings?select=setting_value&setting_key=eq.pix_key&limit=1',{headers:headersPublicos()});if(!resposta.ok)throw new Error();const dados=await resposta.json();if(dados.length){chavePixCasal=dados[0].setting_value;localStorage.setItem('chavePix',chavePixCasal);document.getElementById('config-pix').value=chavePixCasal}}catch{statusPix('Usando a configuração salva neste navegador.',true)}}
async function salvarPix(){const token=await tokenAdmin();const valor=document.getElementById('config-pix').value.trim();if(!token){mensagemAdmin('Entre antes de salvar o PIX.',true);return}if(!valor){statusPix('Cole um código PIX.',true);return}const botao=document.getElementById('btn-salvar-pix');botao.disabled=true;statusPix('Salvando...');try{const resposta=await fetch(SUPABASE_URL+'/rest/v1/site_settings?on_conflict=setting_key',{method:'POST',headers:headersPublicos({Authorization:'Bearer '+token,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'}),body:JSON.stringify({setting_key:'pix_key',setting_value:valor,updated_at:new Date().toISOString()})});if(!resposta.ok)throw new Error('O Supabase não permitiu salvar.');chavePixCasal=valor;localStorage.setItem('chavePix',valor);statusPix('PIX salvo para todos os convidados.')}catch(erro){statusPix(erro.message,true)}finally{botao.disabled=!sessaoAdmin}}

let presentesAtuais=lerListaSalva('listaPresentes',[]);
async function carregarPresentesGlobais(){const area=document.getElementById('container-presentes');area.innerHTML='<div class="empty-gifts"><p class="hand">Só um instante...</p><p>Estamos abrindo a lista.</p></div>';try{const resposta=await fetch(SUPABASE_URL+'/rest/v1/gifts?select=id,name,total_value,total_quotas,card_link,image_url,sort_order&active=eq.true&order=sort_order.asc,id.asc',{headers:headersPublicos()});if(!resposta.ok)throw new Error();presentesAtuais=(await resposta.json()).map(p=>({id:Number(p.id),nome:p.name,valorTotal:Number(p.total_value),totalCotas:Number(p.total_quotas),linkCartao:p.card_link||'',imagem:p.image_url||'',ordem:Number(p.sort_order)||0}))}catch{console.warn('Lista global indisponível; usando o cache local.')}renderizarPresentes()}
function renderizarPresentes(){const site=document.getElementById('container-presentes');const admin=document.getElementById('lista-admin-presentes');site.innerHTML='';admin.innerHTML='';if(!presentesAtuais.length){site.innerHTML='<div class="empty-gifts"><p class="hand">Estamos preparando cada detalhe com carinho.</p><p>A lista estará disponível em breve.</p></div>';admin.innerHTML='<p>Nenhum presente cadastrado.</p>'}presentesAtuais.forEach((presente,index)=>{const cota=presente.valorTotal/presente.totalCotas;const nome=escaparHtml(presente.nome);const imagem=presente.imagem?`<figure class="gift-image"><img src="${escaparHtml(presente.imagem)}" alt="${nome}" loading="lazy" decoding="async"></figure>`:'<div class="gift-image gift-image-placeholder"><span>com carinho</span></div>';site.insertAdjacentHTML('beforeend',`<article class="card-presente reveal">${imagem}<span class="gift-number">PRESENTE ${String(index+1).padStart(2,'0')}</span><h3>${nome}</h3><div class="info-preco"><p>Valor total<br>${formatarMoeda(presente.valorTotal)}</p><p class="quota">${formatarMoeda(cota)} <small>/ cota</small></p></div><div class="controle-cotas"><label for="qtd-${presente.id}">Quantas cotas?</label><input type="number" id="qtd-${presente.id}" min="1" max="${presente.totalCotas}" value="1"></div><button class="button" type="button" onclick="abrirCheckout(${index},${cota})">Escolher presente</button></article>`);const desabilitado=sessaoAdmin?'':' disabled';admin.insertAdjacentHTML('beforeend',`<div class="item-admin"><div><strong>${nome}</strong><small>${presente.totalCotas} cotas · ${formatarMoeda(presente.valorTotal)}</small></div><div class="item-admin-actions"><button class="btn-editar-presente" onclick="editarPresente(${presente.id})"${desabilitado}>Editar</button><button class="btn-excluir-presente" onclick="excluirPresente(${presente.id})"${desabilitado}>Excluir</button></div></div>`)});localStorage.setItem('listaPresentes',JSON.stringify(presentesAtuais));observarEntradas()}

let presenteEditando=null;
function statusPresente(texto,erro=false){const area=document.getElementById('presente-admin-status');area.textContent=texto;area.classList.toggle('error',erro)}
function mostrarPreviaImagem(url,texto){document.getElementById('image-preview-admin-img').src=url;document.getElementById('image-preview-admin-text').textContent=texto;document.getElementById('image-preview-admin').hidden=false}
function editarPresente(id){if(!sessaoAdmin)return;const p=presentesAtuais.find(item=>item.id===Number(id));if(!p)return;presenteEditando={...p};document.getElementById('titulo-form-presente').textContent='Editar presente';document.getElementById('nome-prod').value=p.nome;document.getElementById('valor-prod').value=p.valorTotal;document.getElementById('cotas-prod').value=p.totalCotas;document.getElementById('link-pgto-prod').value=p.linkCartao;document.getElementById('imagem-prod').value='';document.getElementById('btn-salvar-presente').textContent='Salvar alterações';document.getElementById('btn-cancelar-edicao').hidden=false;if(p.imagem)mostrarPreviaImagem(p.imagem,'Imagem atual');document.getElementById('form-add-presente').scrollIntoView({behavior:'smooth',block:'center'})}
function cancelarEdicaoPresente(){presenteEditando=null;document.getElementById('form-add-presente').reset();document.getElementById('titulo-form-presente').textContent='Novo presente';document.getElementById('btn-salvar-presente').textContent='Publicar presente';document.getElementById('btn-cancelar-edicao').hidden=true;document.getElementById('image-preview-admin').hidden=true;statusPresente('')}
async function buscarImagemProduto(link,token){const resposta=await fetch(SUPABASE_URL+'/functions/v1/product-image',{method:'POST',headers:headersPublicos({Authorization:'Bearer '+token,'Content-Type':'application/json'}),body:JSON.stringify({url:link})});const dados=await resposta.json().catch(()=>({}));if(!resposta.ok)throw new Error(dados.error||'Não foi possível obter a foto.');return dados}
document.getElementById('form-add-presente').addEventListener('submit',async function(evento){evento.preventDefault();const token=await tokenAdmin();if(!token)return;const botao=document.getElementById('btn-salvar-presente');const nome=document.getElementById('nome-prod').value.trim();const valor=Number(document.getElementById('valor-prod').value);const cotas=Number(document.getElementById('cotas-prod').value);const link=document.getElementById('link-pgto-prod').value.trim();let imagem=document.getElementById('imagem-prod').value.trim();botao.disabled=true;statusPresente('Salvando...');try{if(!imagem&&presenteEditando&&link===presenteEditando.linkCartao)imagem=presenteEditando.imagem;if(!imagem&&link){const dados=await buscarImagemProduto(link,token);imagem=dados.image_url;mostrarPreviaImagem(imagem,'Foto encontrada')}const corpo={name:nome,total_value:valor,total_quotas:cotas,card_link:link||null,image_url:imagem||null,active:true,updated_at:new Date().toISOString()};let metodo='POST';let url=SUPABASE_URL+'/rest/v1/gifts?select=id';if(presenteEditando){metodo='PATCH';url=SUPABASE_URL+'/rest/v1/gifts?id=eq.'+presenteEditando.id+'&select=id'}else corpo.sort_order=Math.max(0,...presentesAtuais.map(p=>p.ordem))+10;const resposta=await fetch(url,{method:metodo,headers:headersPublicos({Authorization:'Bearer '+token,'Content-Type':'application/json',Prefer:'return=representation'}),body:JSON.stringify(corpo)});if(!resposta.ok)throw new Error('Não foi possível salvar o presente.');cancelarEdicaoPresente();await carregarPresentesGlobais();statusPresente('Presente salvo.')}catch(erro){statusPresente(erro.message,true)}finally{botao.disabled=!sessaoAdmin}});
async function excluirPresente(id){const token=await tokenAdmin();const p=presentesAtuais.find(item=>item.id===Number(id));if(!token||!p||!confirm(`Excluir “${p.nome}” da lista?`))return;const resposta=await fetch(SUPABASE_URL+'/rest/v1/gifts?id=eq.'+id,{method:'DELETE',headers:headersPublicos({Authorization:'Bearer '+token})});if(resposta.ok)await carregarPresentesGlobais();else statusPresente('Não foi possível excluir.',true)}
function abrirCheckout(index,valorCota){const p=presentesAtuais[index];if(!p)return;const campo=document.getElementById('qtd-'+p.id);const qtd=Math.min(p.totalCotas,Math.max(1,Number(campo.value)||1));const total=valorCota*qtd;campo.value=qtd;document.getElementById('resumo-compra').innerHTML=`<strong>${qtd} cota(s)</strong> de <strong>${escaparHtml(p.nome)}</strong><br><b>${formatarMoeda(total)}</b>`;document.getElementById('aviso-valor-pix').textContent=`Informe o valor exato de ${formatarMoeda(total)} no seu banco.`;const areaPix=document.getElementById('area-pix');const qr=document.getElementById('qr-code-img');areaPix.hidden=!chavePixCasal;if(chavePixCasal)qr.src='https://api.qrserver.com/v1/create-qr-code/?size=200x200&data='+encodeURIComponent(chavePixCasal);const areaCartao=document.getElementById('area-cartao');areaCartao.hidden=!p.linkCartao;if(p.linkCartao)document.getElementById('btn-link-pagamento').href=p.linkCartao;document.getElementById('modal-pagamento').hidden=false;document.body.classList.add('modal-open')}
function fecharModal(){document.getElementById('modal-pagamento').hidden=true;document.body.classList.remove('modal-open')}
async function copiarPix(){if(!chavePixCasal)return;try{await navigator.clipboard.writeText(chavePixCasal);alert('Código PIX copiado!')}catch{prompt('Copie o código PIX:',chavePixCasal)}}

/* RSVP e mensagens */
async function inserirPublico(tabela,corpo){const resposta=await fetch(`${SUPABASE_URL}/rest/v1/${tabela}`,{method:'POST',headers:headersPublicos({'Content-Type':'application/json',Prefer:'return=minimal'}),body:JSON.stringify(corpo)});if(!resposta.ok){const dados=await resposta.json().catch(()=>({}));throw new Error(dados.message||'Não foi possível enviar agora.')}}
function definirStatus(id,texto,tipo=''){const area=document.getElementById(id);area.textContent=texto;area.className='form-status '+tipo}
document.getElementById('rsvp-form').addEventListener('submit',async function(evento){evento.preventDefault();if(this.website.value)return;const botao=this.querySelector('button[type=submit]');const dados=new FormData(this);botao.disabled=true;definirStatus('rsvp-status','Enviando...');try{await inserirPublico('guest_responses',{guest_name:String(dados.get('name')).trim(),attending:dados.get('attendance')==='sim',guest_count:Number(dados.get('guest_count')),note:String(dados.get('note')||'').trim()||null});definirStatus('rsvp-status','Presença registrada! Obrigado por responder.','success');this.reset();document.getElementById('rsvp-guests').value=1;criarPetalas(innerWidth*.73,innerHeight*.55,16)}catch(erro){definirStatus('rsvp-status',erro.message,'error')}finally{botao.disabled=false}});
document.getElementById('message-form').addEventListener('submit',async function(evento){evento.preventDefault();if(this.website.value)return;const botao=this.querySelector('button[type=submit]');const dados=new FormData(this);botao.disabled=true;definirStatus('message-status','Guardando sua mensagem...');try{await inserirPublico('guest_messages',{guest_name:String(dados.get('name')).trim(),message:String(dados.get('message')).trim()});definirStatus('message-status','Mensagem enviada com carinho!','success');this.reset();criarPetalas(innerWidth*.72,innerHeight*.5,18)}catch(erro){definirStatus('message-status',erro.message,'error')}finally{botao.disabled=false}});

async function carregarRespostasAdmin(){const token=await tokenAdmin();if(!token)return;const area=document.getElementById('lista-admin-rsvp');area.innerHTML='<p>Carregando...</p>';const resposta=await fetch(SUPABASE_URL+'/rest/v1/guest_responses?select=guest_name,attending,guest_count,note,created_at&order=created_at.desc',{headers:headersPublicos({Authorization:'Bearer '+token})});if(!resposta.ok){area.innerHTML='<p>Não foi possível carregar.</p>';return}const dados=await resposta.json();area.innerHTML=dados.length?'':'<p>Nenhuma confirmação ainda.</p>';dados.forEach(item=>area.insertAdjacentHTML('beforeend',`<div class="admin-data"><strong>${escaparHtml(item.guest_name)}</strong><span>${item.attending?'Vai comparecer':'Não comparece'}</span><span>${item.guest_count} pessoa(s)</span><span>${escaparHtml(item.note||'—')}</span></div>`))}
async function carregarMensagensAdmin(){const token=await tokenAdmin();if(!token)return;const area=document.getElementById('lista-admin-mensagens');area.innerHTML='<p>Carregando...</p>';const resposta=await fetch(SUPABASE_URL+'/rest/v1/guest_messages?select=guest_name,message,created_at&order=created_at.desc',{headers:headersPublicos({Authorization:'Bearer '+token})});if(!resposta.ok){area.innerHTML='<p>Não foi possível carregar.</p>';return}const dados=await resposta.json();area.innerHTML=dados.length?'':'<p>Nenhuma mensagem ainda.</p>';dados.forEach(item=>area.insertAdjacentHTML('beforeend',`<div class="admin-data message"><strong>${escaparHtml(item.guest_name)}</strong><span>${escaparHtml(item.message)}</span><time>${new Date(item.created_at).toLocaleDateString('pt-BR')}</time></div>`))}

document.getElementById('modal-pagamento').addEventListener('click',evento=>{if(evento.target.id==='modal-pagamento')fecharModal()});
document.addEventListener('keydown',evento=>{if(evento.key==='Escape'){fecharModal();fecharFoto();navLinks.classList.remove('open');menuToggle.classList.remove('open')}});

restaurarSessaoAdmin();carregarPixGlobal();carregarPresentesGlobais();observarEntradas();
if(location.hash)requestAnimationFrame(()=>{const alvo=document.querySelector(location.hash);alvo?.querySelectorAll('.reveal').forEach(item=>item.classList.add('visible'));alvo?.scrollIntoView({block:'start'})});
